version: '3.6' 
services:
  mongo:
    image: mongo:latest
    hostname: test_mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=records
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports: 
      - 8080:5000
    depends_on:
      - mongo
