version: '3.6' 
services:
  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: user
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: user
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports: 
      - 8080:5000 
  
